on:
  push:
  workflow_dispatch:

jobs:
  job1:
    name: echo org vars
    runs-on: self-hosted
    steps:
    - name: Use variables
      run: |
        echo "repository variable : ${{ vars.REPOSITORY_VAR }}"
        echo "organization variable : ${{ vars.ORGANIZATION_VAR }}"
        echo "overridden variable : ${{ vars.OVERRIDE_VAR }}"
        echo "variable from shell environment : $env_var"
        echo "image repository : ${{ vars.IMAGE_REPOSITORY }}"
        echo "github env : ${{ vars.GITHUB_ENV }}"

